### ISSUE TITLE
How can i generate frontend ui with generate command?

### ISSUE THREAD

**Issue by deervarse** [gin-admin/gin-admin-cli#19]
Hi, 

It seems that if I call gin-admin-cli gen without a json/yaml config file, the frontend ui is not created even if I specify the fe-dir value. Looking at the code, it seems that the frontend ui-related values must be set in the json/yaml file to generate code in the fe-dir entered when calling cli. right?

Can you provide yaml example for generate frontend ui? I would like to simply add a record struct and check the record list through the created top UI.

**Comment by deervarse** [comment]
For example,

```
- name: Record
  comment: just record
  disable_pagination: false
# This means you are going to commit the db query with gorm, right?
  fill_gorm_commit: true 
  fill_router_prefix: true
  generate_fe: true
  fe_tpl: react # react/react-v5-i18n
# I don't know how can i fill it ...
#  fe_mapping: # tpl -> file
#    -hi: test
#    -look: tab
  tpl_type: crud # crud/tree
  fields:
    - name: Comment
      type: string
      comment: recorded at app build time
      gorm_tag: "size:128;"
      form:
        binding_tag: "required,max=128"
    - name: Seq
      type: int
      comment: private seq of record
```

**Comment by deervarse** [comment]
Umm... This may seem obvious to someone.
This is what I figured out while shovel, I hope it helps someone.

```
- name: ExampleRecord
  module: OFFICE
  comment: example structs for write config yaml
  # set false if you need to show with pagination when get all rows
  disable_pagination: false
  fill_gorm_commit: true
  # Set to true to include the module name in the API path, such as `/api/v1/office/example-records'
  fill_router_prefix: true
  force_write: true
  # You must set this value to true to generate the frontend component code based on the template.
  generate_fe: true
  # disable to create default fields that id, createdAt, updatedAt etc.
  disable_default_fields: false
  tpl_type: crud # crud/tree
  fe_tpl: react # react/react-v5-i18n
  fe_mapping: # tpl -> file
    services.typings.d.ts.tpl: src/services/office/example_record_typing.d.ts
    services.index.ts.tpl: src/services/office/example_record_service.ts
    pages.index.tsx.tpl: src/pages/office/ExampleRecord/index.tsx
    pages.components.SaveForm.tsx.tpl: src/pages/office/ExampleRecord/components/SaveForm.tsx
  extra:
    # need when generate code
    ImportService: office/example_record_service
    ActionText: Option
    AddTitle: Add
    EditTitle: Edit
    DelTip: Delete
    SubmitText: Submit
    ResetText: Reset
    SaveSuccessMessage: Saved.
    DeleteSuccessMessage: Deleted.
  fields:
    - name: ServerGroupId
      type: int
      query:
        name: ServerGroupId
        in_query: true
        form_tag: server_group_id
        op: =
      gorm_tag: "type:tinyint unsigned;"
      comment: id of server group info table
      form:
        binding_tag: "type:int,required"
      extra:
        Label: ServerGroupId
        InColumn: "true"
        Required: true
    - name: Version
      type: string
      comment: app build version
      gorm_tag: "size:16;index"
      query:
        name: SearchVersion
        in_query: true
        form_tag: version
        op: LIKE
      form:
        binding_tag: "required,max=16"
      extra:
        Label: Version
        InColumn: "true"
        Required: true
```
